[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "public"

  [build.environment]
    SUPABASE_URL = "https://damtkcemrxbrvsjiyiqd.supabase.co"
    SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhbXRrY2VtcnhicnZzaml5aXFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NDc0NTM2MjYsImV4cCI6MTk2MzAyOTYyNn0.YMTHZSbBNKwGRO2Y_MBzaOB_FkucHCzUJPk115mlU1M"

[dev]
  command = "remix watch"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"
